### ISSUE TITLE
robot-shop: mongo pod failing:  chown: changing ownership of '/data/db': Operation not permitted

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-demo-apps#1]
Seeing below failure of mongo pod when deploying robot-shop on OCP 3

chown: changing ownership of '/data/db': Operation not permitted

**Comment by pranavgaikwad** [comment]
Should be fixed through : https://github.com/fusor/mig-demo-apps/commit/a8bb883ab2f4da3761f294593fc68ece03452f62
